import { convertToExcalidrawElements } from "@excalidraw/excalidraw";

const generateId = () => Math.random().toString(36);
const elements = convertToExcalidrawElements([
  // Start box
  {
    id: generateId(),
    type: "rectangle",
    x: 100,
    y: 100,
    width: 100,
    height: 50,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#D1FAE5",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    boundElements: [],
  },
  // Process box
  {
    id: generateId(),
    type: "rectangle",
    x: 250,
    y: 100,
    width: 120,
    height: 50,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#DBEAFE",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    boundElements: [],
  },
  {
    id: generateId(),
    type: "rectangle",
    x: 410,
    y: 100,
    width: 100,
    height: 50,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#FECACA",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    boundElements: [],
  },
  // Arrows
  {
    id: generateId(),
    type: "arrow",
    x: 200,
    y: 125,
    width: 50,
    height: 0,
    points: [
      [0, 0],
      [50, 0],
    ],
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 0,
    opacity: 100,
    groupIds: [],
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    isDeleted: false,
    boundElements: [],
  },
  {
    id: generateId(),
    type: "arrow",
    x: 370,
    y: 125,
    width: 40,
    height: 0,
    points: [
      [0, 0],
      [40, 0],
    ],
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 0,
    opacity: 100,
    groupIds: [],
    seed: Math.floor(Math.random() * 100000),
    version: 1,
    versionNonce: Math.floor(Math.random() * 100000),
    isDeleted: false,
    boundElements: [],
  },
])
export default elements